### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alphaRed03**
Bridges add on of secureshift

### CODE REVIEW

**Review by abitmore — COMMENTED** [review]
Although BTS is listed, it doesn't seem working. Got error messages like `Oops, pair bts to btc is unavailable.`

**Comment by alphaRed03** [comment]
Thanks for information it was forwarded to technician team to over view the
issue

**Comment by alphaRed03** [comment]
Go update from te currently bts to any pair unavailable but any crypto to
bts was available .
Like: btc ti bts or xmr to bts this pairs are active

**Review by abitmore — APPROVED** [review]
Thanks.

**Comment by alphaRed03** [comment]
Thanks 🤩

**Pull request merged**
